#pragma once
#include "pefi.h"

#define EFI_GLOBAL_VARIABLE_GUID {0x8BE4DF61, 0x93CA, 0x11D2, {0xAA,0x0D,0x00,0xE0,0x98,0x03,0x2B,0x8C}}
extern EFI_GUID gEfiGlobalVariableGuid;
#define EFI_IMAGE_SECURITY_DATABASE_GUID {0xD719B2CB, 0x3D3A, 0x4596, {0xA3,0xBC,0xDA,0xD0,0xE8,0x5B,0x12,0x7F}}
extern EFI_GUID gEfiImageSecurityDatabaseGuid;

#define EFI_VARIABLE_NON_VOLATILE 0x00000001
#define EFI_VARIABLE_BOOTSERVICE_ACCESS 0x00000002
#define EFI_VARIABLE_RUNTIME_ACCESS 0x00000004
#define EFI_VARIABLE_HARDWARE_ERROR_RECORD 0x00000008
#define EFI_VARIABLE_AUTHENTICATED_WRITE_ACCESS 0x00000010
#define EFI_VARIABLE_TIME_BASED_AUTHENTICATED_WRITE_ACCESS 0x00000020
#define EFI_VARIABLE_APPEND_WRITE 0x00000040

#define EFI_LANG_VARIABLE_NAME L"Lang"
#define EFI_LANG_CODES_VARIABLE_NAME L"LangCodes"
#define EFI_TIMEOUT_VARIABLE_NAME L"Timeout"
#define EFI_PLATFORM_LANG_VARIABLE_NAME L"PlatformLang"
#define EFI_PLATFORM_LANG_CODES_VARIABLE_NAME L"PlatformLangCodes"
#define EFI_CON_IN_VARIABLE_NAME L"ConIn"
#define EFI_CON_OUT_VARIABLE_NAME L"ConOut"
#define EFI_ERR_OUT_VARIABLE_NAME L"ErrOut"
#define EFI_BOOT_ORDER_VARIABLE_NAME L"BootOrder"
#define EFI_BOOT_NEXT_VARIABLE_NAME L"BootNext"
#define EFI_BOOT_CURRENT_VARIABLE_NAME L"BootCurrent"
#define EFI_BOOT_OPTION_SUPPORT_VARIABLE_NAME L"BootOptionSupport"
#define EFI_DRIVER_ORDER_VARIABLE_NAME L"DriverOrder"
#define EFI_OS_INDICATIONS_VARIABLE_NAME L"OsIndications"
#define EFI_OS_INDICATIONS_SUPPORTED_VARIABLE_NAME L"OsIndicationsSupported"
#define EFI_SETUP_MODE_NAME L"SetupMode"
#define EFI_SECURE_BOOT_MODE_NAME L"SecureBoot"
#define EFI_SIGNATURE_SUPPORT_NAME L"SignatureSupport"
#define EFI_PK_VARIABLE_NAME L"PK"
#define EFI_KEK_VARIABLE_NAME L"KEK"
#define EFI_DB_VARIABLE_NAME L"db"
#define EFI_DBX_VARIABLE_NAME L"dbx"
#define EFI_DBT_VARIABLE_NAME L"dbt"
#define EFI_VENDOR_KEYS_VARIABLE_NAME L"VendorKeys"

#define EFI_OS_INDICATIONS_BOOT_TO_FW_UI 0x0000000000000001ULL
#define EFI_OS_INDICATIONS_TIMESTAMP_REVOCATION 0x0000000000000002ULL
#define EFI_OS_INDICATIONS_FILE_CAPSULE_DELIVERY_SUPPORTED 0x0000000000000004ULL
#define EFI_OS_INDICATIONS_FMP_CAPSULE_SUPPORTED 0x0000000000000008ULL
#define EFI_OS_INDICATIONS_CAPSULE_RESULT_VAR_SUPPORTED 0x0000000000000010ULL
#define EFI_OS_INDICATIONS_START_PLATFORM_RECOVERY 0x0000000000000040ULL
